server:
  port: 9087

spring:
logging:
  file: logs/asset-manager.log
  pattern:
      console: "%d %-5level %logger : %msg%n"
      file: "%d %-5level [%thread] %logger : %msg%n"
  level:
    org.springframework.web: DEBUG
    org.hibernate: ERROR

spring.profiles: dev

